name = "jsa-mobile-proxy"
compatibility_date = "2025-09-06"
send_metrics = true
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = true
minify = false
logpush = true

[observability]
enabled = true
head_sampling_rate = 0.1

## JKF形式の棋譜データをKVに保存する
[[kv_namespaces]]
binding = "KV"
id = "88c586c849b0403cb2fdda3cb107b2f1"

## BIN形式の棋譜データをR2に保存する
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "jsa-mobile"

## D1に棋譜データを保存する
[[d1_databases]]
binding = "DB"
database_name = "jsamobile"
database_id = "e103ae8d-9f03-4e70-a091-90ba9acf9e27"
migrations_dir = "prisma/migrations"

[triggers]
crons = ['*/5 * * * *', '*/1 * * * *']

[dev]
ip = "0.0.0.0"
port = 28787
local_protocol = "http"
