name = "jsa-mobile-proxy"
compatibility_date = "2025-09-06"
send_metrics = true
compatibility_flags = ["nodejs_compat_v2"]
logpush = true

[env.prod]
workers_dev = false
preview_urls = false
minify = true
routes = [
  { pattern = "jsam.qleap.jp/api/games", custom_domain = false },
  { pattern = "jsam.qleap.jp/api/players", custom_domain = false },
]

[env.dev]
workers_dev = true
preview_urls = true
minify = false
routes = [
  { pattern = "jsam-dev.qleap.jp/api/games", custom_domain = false },
  { pattern = "jsam-dev.qleap.jp/api/players", custom_domain = false },
]

[env.prod.triggers]
crons = ['*/5 * * * *', '0 * * * *', '0 21 * * *']

[env.dev.triggers]
crons = ['*/5 * * * *', '0 * * * *', '0 21 * * *']

[env.prod.observability]
enabled = true

[env.dev.observability]
enabled = true

[[env.prod.kv_namespaces]]
binding = "RATE_LIMITTER"
id = "60fc87bcd9a443b385b186a67864ec8b"

[[env.dev.kv_namespaces]]
binding = "RATE_LIMITTER"
id = "60fc87bcd9a443b385b186a67864ec8b"

## BIN形式の棋譜データをR2に保存する
[[env.prod.r2_buckets]]
binding = "BUCKET"
bucket_name = "jsa-mobile"

[[env.dev.r2_buckets]]
binding = "BUCKET"
bucket_name = "jsa-mobile"

## D1に棋譜データを保存する
[[env.prod.d1_databases]]
binding = "DB"
database_name = "jsamobile"
database_id = "e103ae8d-9f03-4e70-a091-90ba9acf9e27"
migrations_dir = "prisma/migrations"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "jsamobile"
database_id = "e103ae8d-9f03-4e70-a091-90ba9acf9e27"
migrations_dir = "prisma/migrations"

[dev]
ip = "0.0.0.0"
port = 18787
local_protocol = "http"
