export enum Tournament {
  ABEMA = 'AbemaTVトーナメント',
  ASAHI = '朝日杯将棋オープン戦',
  MAINAVI = 'マイナビ女子オープン',
  JT = '日本シリーズJT',
  SIRATAKI = '白瀧あゆみ杯',
  KURASIKI = '倉敷藤花戦',
  KAKOGAWA = '加古川青流戦',
  JORYU_OUZA = '女流王座戦',
  JORYU_MEIJIN = '女流名人戦',
  JORYU_OUI = '女流王位戦',
  JORYU_OUSHOU = '女流王将戦',
  JORYU_RANK = '女流順位戦',
  HAKUREI = '白玲戦',
  SEIREI = '清麗戦',
  MEIJIN = '名人戦',
  TATSUJIN = '達人戦',
  SINJIN = '新人王戦',
  RYUO = '竜王戦',
  EIOU = '叡王戦',
  OUZA = '王座戦',
  KIOU = '棋王戦',
  KISEI = '棋聖戦',
  RANK = '順位戦',
  OUI = '王位戦',
  OUSHOU = '王将戦'
}
